### PR TITLE
Update Finagle, Util to 22.4

### PR DESCRIPTION
**Pull request by mishriky**

### CODE REVIEW

**Comment by bpholt** [comment]
Thanks! There were some changes made in 21.9.0 that may cause issues, so I'd like to look at those before we merge. (I'm away from my computer at the moment or I'd be more specific.)

Also, I think technically Twitter released 22.4.0, but there were no changes from 22.3.0. We may still want to go to that version to facilitate eventually having Scala Steward initiate these kinds of updates.

**Comment by mishriky** [comment]
Thanks for the quick feedback. Changed to 22.4
Let me know if I can help with the 21.9.0 changes

**Comment by mishriky** [comment]
@bpholt curious if I can help with anything to get this change merged/released

**Comment by bpholt** [comment]
I think it's ok to move forward with this, but we need to wait for (at least) #460 so that we can actually publish a new version of this library.

[This is the change](https://github.com/twitter/scrooge/commit/8d768ca620a33d18b89492a7a2077007cedb6e7d) that was giving me pause before. It removed higher kinded types from the Finagle traits generated by Scrooge (and Finagle itself made it pretty difficult to reintroduce them, since it uses [reflection with hardcoded trait names](https://github.com/twitter/finagle/blob/e3963fcd45f74c02c3f63c79f8c733ce5208fa63/finagle-thrift/src/main/scala/com/twitter/finagle/thrift/ThriftUtil.scala#L148) to start a Finagle server). We work around this at Dwolla by using the [Scalafix rules in our async-utils library](https://github.com/dwolla/async-utils#scalafix-rule) to rewrite the Scrooge-generated code to something that keeps the higher-kinded traits but is still compatible with Finagle.

**Comment by bpholt** [comment]
Incorporated into #461.

**Pull request closed without merging**
